title: Ferio's Chaotic World
email: feriobrahmana5@gmail.com
description: Personal notes and ideas by Ferio Brahmana on complex systems, biology, and life.
baseurl: ""
url: "https://feriobrahmana.github.io"

theme: minima

plugins:
  - jekyll-feed

# Show posts with future dates so scheduled private letters appear
future: true
